name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      release_tag:
        description: '发布标签'
        required: true
        type: string

jobs:
  build_app:
    runs-on: windows-latest
    env:
      artifact_name: out_app_windows_x64_singleFile
      arch: win-x64
      trim_assets: 'false'
      package: singleFile
    name: Build_windows_x64_singleFile
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
          ref: ${{ github.event_name != 'workflow_dispatch' && github.ref || github.event.inputs.release_tag }}

      - name: List files
        run: ls

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.20

      # Add  MSBuild to the PATH
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build application
        env:
          trim_assets: ${{ env.trim_assets }}
          package: ${{ env.package }}
          arch: win-x64
        run: |
          ls
          pwsh -ep Bypass -c ./tools/release-gen/publish.ps1 false x64

      - name: Upload exe to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}
          path: |
            ./out/*
